### ISSUE TITLE
Link to Pardis is broken

### ISSUE THREAD

**Issue by Blaisorblade** [epfldata/dblab#48]
I currently get 404 on the link to https://github.com/amirsh/pardis from the README, and googling pardis (or variations) doesn't help me. The only related link I've found is https://github.com/epfldata/c-scala. Would you mind updating the README?

**Comment by christophkoch** [comment]
dblab and the pardis compiler are not released yet. Will be soon.

**Comment by jduewel** [comment]
Are there any updates on this topic?

**Comment by amirsh** [comment]
We are still working on it.
We will make it available after publication.
